### ISSUE TITLE
More info on parse_phenix_40X

### ISSUE THREAD

**Issue by michaelquez97** [MannLabs/SPARCStools#12]
Hello!

Thank you for this great package. I am trying to get it running on my data acquired at 40X with the Opera Phenix. I was wondering if it would be possible to provide a bit more information on the difference between parse_phenix and parse_phenix_40X? I ran both on my data and the 40X version seemed to combine the wells in each column into the same well stacked on top of each other. I also ran the normal parse_phenix function but the output was not compatible with the downstream stitching function (my other data has been compatible taken at 10X). 

Any info on this would be amazing! Thank you.

**Comment by sophiamaedler** [comment]
Hi @michaelquez97, 

We actually recently completely reworked the stitching and parsing code and have included it in a new repo (https://github.com/MannLabs/scPortrait). The new code is more robust from a coding point of view and also implements a few new features (e.g. multithreaded stitching for much faster performance as well as writing to new output formats like spatialdata). I would recommend checking it out and switching to using that code in the future as we will not maintain this repo long-term. 

There are two tutorial notebooks on parsing (https://mannlabs.github.io/scPortrait/html/pages/tools/parsing/example_parsing_notebook.html) and stitching (https://mannlabs.github.io/scPortrait/html/pages/tools/stitching/example_stitching_notebook.html) data available in the documentation that should hopefully get you started with the package quickly. The repo is currently still under heavy development so the documentation is unfortunately not quite complete yet. In case you get stuck anywhere with anything not explained in the example notebooks feel free to reach out in the other repo with a git issue! Happy to help. 

Now briefly to answer your question:

The parse_phenix_40X function was originally developed for a relatively niche use-case we had with our data. If you image large areas you might have noticed that the Harmony software allows you at most to image 2999 image tiles per well. Especially at large magnification levels this is not always sufficient to completely image a sample. So we developed a custom plate layout that split the actual area to be imaged into individual wells that still have 10% overlap at the edges to basically trick the Opera Phenix to image a larger continuous area than its settings normally allow. During stitching we then of course wanted to combine these "wells" back together into one final stitched object. To handle this use case I wrote the parse_phenix_40X function which does exactly that and fixed our problem but from the view point of a code user this is of course very confusing and intransparent. This among other issues was the reason for the complete code redesign. 

I am guessing that you probably did not acquire your data with this specific niche use case. So it's not surprising that the parse_phenix_40X function did not give you the intended results. I am a little surprised though that you encountered issues with the regular parsing function. What was the specific issue? In general the code should be magnification agnostic so I am guessing whatever error you encountered does not have to do specifically with the 40X magnification but with something else. 

If you could share your code for parsing and stitching and the resulting error messages I would be happy to take a look and to see if I can figure out what the problem was.

**Comment by michaelquez97** [comment]
Thanks so much for your detailed response and for directing me to the more updated github. I totally missed this before so I will check this out now. 

Your explanation on the parse_phenix_40X function makes total sense! I have run into this on the Phenix too so I understand. For this dataset I don't need this functionality, so I won't use it. 

The error I have encountered a couple times is below (I only encountered this with my 40X images for whatever reason): 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/ashlar/reg.py:709, in EdgeAligner.register_pair(self, t1, t2)
    708 try:
--> 709     shift, error = self._cache[key]
    710 except KeyError:
    711     # We test a series of increasing overlap window sizes to help avoid
    712     # missing alignments when the stage position error is large relative
   (...)
    717     # the tile size. If the nominal overlap is already 10% or greater,
    718     # we only use that one size.

KeyError: (0, 1)

During handling of the above exception, another exception occurred:

UFuncTypeError                            Traceback (most recent call last)
Cell In[49], line 1
----> 1 generate_stitched(input_dir,
      2                     slidename,
      3                     pattern,
      4                     output_dir,
      5                     overlap,
      6                     crop = crop ,
      7                     stitching_channel = stitching_channel,
      8                     filetype = output_filetype,
      9                     plot_QC = True,
     10                     do_intensity_rescale = False,
     11                     rescale_range = rescale_range)

File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/sparcstools/stitch.py:338, in generate_stitched(input_dir, slidename, pattern, outdir, overlap, max_shift, stitching_channel, crop, plot_QC, filetype, WGAchannel, do_intensity_rescale, rescale_range, no_rescale_channel, export_XML, return_tile_positions, channel_order, filter_sigma)
    336 print("performing stitching on channel ", stitching_channel, "with id number ", str(channel_id))
    337 aligner = reg.EdgeAligner(slide, channel=channel_id, filter_sigma=filter_sigma, verbose=True, do_make_thumbnail=False, max_shift = max_shift)
--> 338 aligner.run()  
    340 #generate some QC plots
    341 if plot_QC:

File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/ashlar/reg.py:507, in EdgeAligner.run(self)
    505 self.check_overlaps()
    506 self.compute_threshold()
--> 507 self.register_all()
    508 self.build_spanning_tree()
    509 self.calculate_positions()

File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/ashlar/reg.py:622, in EdgeAligner.register_all(self)
    620         sys.stdout.write('\r    aligning edge %d/%d' % (i, n))
    621         sys.stdout.flush()
--> 622     self.register_pair(t1, t2)
    623 if self.verbose:
    624     print()

File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/ashlar/reg.py:731, in EdgeAligner.register_pair(self, t1, t2)
    726 shift, _ = min(results, key=lambda r: r[1])
    727 # Extract the images from the nominal overlap window but with the
    728 # shift applied to the second tile's position, and compute the error
    729 # metric on these images. This should be even lower than the error
    730 # computed above.
--> 731 _, o1, o2 = self.overlap(key[0], key[1], shift=shift)
    732 error = utils.nccw(o1, o2, self.filter_sigma)
    733 self._cache[key] = (shift, error)

File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/ashlar/reg.py:763, in EdgeAligner.overlap(self, t1, t2, min_size, shift)
    762 def overlap(self, t1, t2, min_size=0, shift=None):
--> 763     its = self.intersection(t1, t2, min_size, shift)
    764     img1 = self.crop(t1, its.offsets[0], its.shape)
    765     img2 = self.crop(t2, its.offsets[1], its.shape)

File ~/miniconda3/envs/stitching2/lib/python3.10/site-packages/ashlar/reg.py:754, in EdgeAligner.intersection(self, t1, t2, min_size, shift)
    752 corners1 = self.metadata.positions[[t1, t2]]
    753 if shift is not None:
--> 754     corners1[1] += shift
    755 corners2 = corners1 + self.metadata.size
    756 return Intersection(corners1, corners2, min_size)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

I was able to fix this by changing `corners1[1] += shift` to `corners1[1] = corners1[1] + shift`, and everything now works properly so it is not a huge issue. I just wanted to bring to your attention in case it is helpful. 

Thanks so much! Your package has been very useful to me - I appreciate all your hard work.
